In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib  # Thư viện để lưu mô hình

# 1. Đọc dữ liệu
data = pd.read_csv('health_dataset.csv')

# 2. Kiểm tra dữ liệu
print(data.head())
print(data.info())

# 3. Phân chia input (X) và output (y)
X = data[['body temperature', 'pulse', 'SpO2']]  # Cột đầu vào
y = data['Status']  # Cột nhãn

# 4. Chia dữ liệu thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Huấn luyện mô hình Random Forest
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# 6. Dự đoán và đánh giá
y_pred = model.predict(X_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 7. Lưu mô hình đã huấn luyện
joblib.dump(model, 'health_model.pkl')
print("Mô hình đã được lưu vào file 'health_model.pkl'.")

# 8. Dự đoán mới (ví dụ)
sample_data = np.array([[36.8, 80, 98]])  # Một hàng dữ liệu mới (nhiệt độ, nhịp tim, SpO2)
loaded_model = joblib.load('health_model.pkl')  # Tải lại mô hình từ file
print("Predicted Status:", loaded_model.predict(sample_data))




   pulse  body temperature  SpO2  Status
0     70              36.0    99       0
1     70              36.0    98       0
2     70              36.0    97       0
3     70              36.0    96       0
4     70              36.1   100       0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5909 entries, 0 to 5908
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   pulse             5909 non-null   int64  
 1   body temperature  5909 non-null   float64
 2   SpO2              5909 non-null   int64  
 3   Status            5909 non-null   int64  
dtypes: float64(1), int64(3)
memory usage: 184.8 KB
None
Confusion Matrix:
 [[215   0   0]
 [  0 473   0]
 [  0   0 494]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       215
           1       1.00      1.00      1.00       473
           2       1.00      1.00      1.00       494

 

C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
